require 'sinatra/base'
require 'sinatra/json'
require 'sinatra/reloader'
require 'sinatra/activerecord'
require 'action_controller'
require 'action_controller/serialization'
require 'active_model_serializers'
